server:
  port: 8082

spring:
  application:
    name: milk-service
  datasource:
    url: jdbc:postgresql://localhost:6432/farm_milk
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

weight:
  service:
    url: http://localhost:8081 