server:
  port: 8081

spring:
  application:
    name: weight-service
  datasource:
    url: jdbc:postgresql://localhost:6432/farm_weight
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true 